#!/usr/bin/env python3
"""Build the local world-land SVG asset from the vendored Natural Earth data.

Development-time tool (pure standard library). The server never downloads
anything at runtime; this script is only re-run when the vendored input or the
projection changes, and its output is committed to the repository.

Input:  tools/vendor_ne_110m_land.geojson  (Natural Earth 110m land, v5.1.2,
        public domain; SHA-256 recorded in THIRD-PARTY-NOTICES.md)
Output: src/ranger_map/static/assets/world-land.svg

The projection is equirectangular (plate carree) onto a 1000x500 viewBox,
matching the projection the browser page uses to place ranger markers, so
coordinates in the page and land shapes always line up.
"""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
INPUT = REPO_ROOT / "tools" / "vendor_ne_110m_land.geojson"
OUTPUT_DIR = REPO_ROOT / "src" / "ranger_map" / "static" / "assets"

# Light and dark variants share geometry; only the ink/paper colours differ.
THEMES = {
    "world-land.svg": {"fill": "#F2E9D8", "stroke": "#2B2B2B", "opacity": "1"},
    "world-land-dark.svg": {"fill": "#434F3E", "stroke": "#E8E3D4", "opacity": "1"},
}

VIEW_W = 1000.0
VIEW_H = 500.0
MIN_POINT_STEP_PX = 0.4  # drop points closer than this to the previous point

SOURCE_URL = (
    "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/"
    "v5.1.2/geojson/ne_110m_land.geojson"
)
SOURCE_VERSION = "v5.1.2"


def project(lon: float, lat: float) -> tuple[float, float]:
    """Equirectangular projection onto the viewBox."""
    x = (lon + 180.0) / 360.0 * VIEW_W
    y = (90.0 - lat) / 180.0 * VIEW_H
    return x, y


def fmt(value: float) -> str:
    """Compact fixed-precision coordinate text without trailing zeros."""
    text = f"{value:.1f}"
    if text.endswith(".0"):
        text = text[:-2]
    return text


def ring_to_path(ring: list[list[float]]) -> str:
    parts: list[str] = []
    last: tuple[float, float] | None = None
    for lon, lat in ring:
        x, y = project(lon, lat)
        if last is not None:
            dx, dy = x - last[0], y - last[1]
            if dx * dx + dy * dy < MIN_POINT_STEP_PX * MIN_POINT_STEP_PX:
                continue
        parts.append(f"{fmt(x)} {fmt(y)}")
        last = (x, y)
    if len(parts) < 3:
        return ""
    return "M" + "L".join(parts) + "Z"


def iter_rings(geometry: dict) -> list[list[list[float]]]:
    if geometry is None:
        return []
    gtype = geometry.get("type")
    if gtype == "Polygon":
        return list(geometry["coordinates"])
    if gtype == "MultiPolygon":
        rings: list[list[list[float]]] = []
        for polygon in geometry["coordinates"]:
            rings.extend(polygon)
        return rings
    return []


def main() -> int:
    raw = INPUT.read_bytes()
    digest = hashlib.sha256(raw).hexdigest()
    doc = json.loads(raw)

    paths: list[str] = []
    for feature in doc["features"]:
        for ring in iter_rings(feature.get("geometry")):
            path = ring_to_path(ring)
            if path:
                paths.append(path)
    body = "".join(paths)

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    for filename, theme in THEMES.items():
        output = OUTPUT_DIR / filename
        svg = "".join(
            [
                '<?xml version="1.0" encoding="UTF-8"?>\n',
                "<!--\n",
                "  World land outline (equirectangular projection, no political boundaries).\n"
                "  Generated by tools/build_land_svg.py - do not edit by hand.\n"
                f"  Source: Natural Earth 110m Land, release {SOURCE_VERSION} (public domain)\n"
                f"  {SOURCE_URL}\n"
                f"  Input SHA-256: {digest}\n"
                f"  Theme: {theme}\n"
                "-->\n",
                f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {int(VIEW_W)} '
                f'{int(VIEW_H)}" preserveAspectRatio="none" class="world-land" '
                'aria-hidden="true" focusable="false">\n',
                f'<path fill-rule="evenodd" fill="{theme["fill"]}" '
                f'stroke="{theme["stroke"]}" stroke-width="1.1" '
                'stroke-linejoin="round" d="',
                body,
                '"/>\n',
                "</svg>\n",
            ]
        )
        output.write_text(svg, encoding="utf-8")
        size_kb = output.stat().st_size / 1024
        print(f"wrote {output} ({size_kb:.1f} KiB, {len(paths)} rings)")
    print(f"  input SHA-256: {digest}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
